name: transcode-worker
image: { repo: "<ecr>/transcode-worker", tag: "dev" }
serviceAccount: { roleArn: "<svc_role_arns.transcode-worker>" }
env:
  REGION: ap-southeast-1
  RAW_BUCKET: "<raw_bucket>"
  TRANSCODED_BUCKET: "<transcoded_bucket>"
  TABLE_NAME: "<table_name>"
  QUEUE_URL: "<queue_url>"
